### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by Nick7hill** [minsangkim142/R-net#1]
line 106 of he proces.py file gives an error while giving the command `' python process.py --process True`'``. the error is ` for key, value in sorted(self.w_dict.iteritems(), key=lambda (k,v): (v,k)):`

**Comment by minsangkim142** [comment]
Hi @Nick7hill, that lines gives syntax error in python3. Try running it in python2, I'll try to make it python3 compatible soon :)

**Comment by Nick7hill** [comment]
thanks  a lot man !

**Comment by Nick7hill** [comment]
` File "process.py", line 335, in <module>
    main()
  File "process.py", line 329, in main
    loader.process_json(Params.data_dir + "dev-v1.1.json", out_dir = Params.dev_dir)
  File "process.py", line 103, in process_json
    self.data = json.load(codecs.open(file_dir,"rb","utf-8"))
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: './data/dev-v1.1.json'
WARNING:CoreNLP_PyWrapper:Killing subprocess 5739`
why is there no file of dev-v1.1.json?
