### ISSUE TITLE
where is 'char_embedding' in model.py initialized?

### ISSUE THREAD

**Issue by huangpeng1126** [minsangkim142/R-net#19]
I can not found where the variable 'char_embedding' is initialized?

Here is the definition code: [self.char_embedding = ...](https://github.com/minsangkim142/R-net/blob/dd77447fa20e8cdad65eac9f5f33f468b159c8d7/model.py#L59)

**Comment by minsangkim142** [comment]
Hi @huangpeng1126, experiments suggest that using pretrained character embeddings does not help improve the performance by much. To reduce GPU memory, I decided to reduce the character embedding space and learn it from scratch and fine tune it. Thanks.

**Comment by huangpeng1126** [comment]
@minsangkim142 , Thank you. I check your code, the parameter 'trainable' is set to 'True'
