### ISSUE TITLE
what were your performance results mate? the EM and F1?

### ISSUE THREAD

**Issue by Nick7hill** [minsangkim142/R-net#2]

**Comment by minsangkim142** [comment]
Currently I am struggling to reduce the gpu memory usage in tensorflow to fit a minibatch of 48 and higher. Until then I can't train with full dataset, as the dataset shows high variance and it won't converge with small mini-batches.

**Comment by minsangkim142** [comment]
Please take a look at ec238d6f7ac57890423298acaf71befbceddf012 and 0523897bbf61db0df75b60dd09ff56cdff7d8310. Now you can check your training set F1 and EM from Tensorboard while training, as well as checking your dev set F1 and EM by changing test = True from params.py file and running the model.py file. If you obtain any results please report the hyperparameters you used with results here so we can share the results and work towards improving the implementation.

**Comment by Nick7hill** [comment]
yeah, sure, thanks a lot! your have done tremendous work in trying to emulate R-net

**Comment by Nick7hill** [comment]
can you please make a blog post about your implementation, it is kind of difficult to correlate the code with the architecture at times, and if you don't mind comment the code at certain places, i suggest jupyter notebooks are better

**Comment by minsangkim142** [comment]
Thanks for your input! I'll look into jupyter notebooks

**Comment by minsangkim142** [comment]
Let's keep all performance related discussions in this issue #12 thanks!
