### ISSUE TITLE
bidirectional_readout

### ISSUE THREAD

**Issue by digitnumber** [minsangkim142/R-net#21]
why do you need `bidirectional_readout`?
because in the paper they use outputs from `attention_match_rnn()` directly as the input to `pointer_network()`

**Comment by minsangkim142** [comment]
Hi @digitnumber, if you look at the [original paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/05/r-net.pdf), they added an extra bidirectional layer before the pointer network. Please check figure 1 of the paper.
" After the original self-matching layer of the passage, we utilize bi-directional GRU to deeply integrate the matching results before feeding them into answer pointer layer. It helps to further propagate the information aggregated by self-matching of the passage." from section 4.2 Main Results.

**Comment by digitnumber** [comment]
Thanks for a quick reply!
Could you please also explain why you used in` def call()` instead of` def __call__()` in `gated_attention_Wrapper`

because I was getting an error 
`__call__     raise NotImplementedError("Abstract method")`

**Comment by minsangkim142** [comment]
I think RNN cell instance in tf natively has `def call()` function. But not sure, changed to `__call__` thanks!
