### ISSUE TITLE
Online demo / realtime user interface

### ISSUE THREAD

**Issue by minsangkim142** [minsangkim142/R-net#23]
From issue #22, we want to make a web based user interface/interaction tool so that users can copy and paste whatever passage context and questions they want and python/tensorflow backend will process the data. 
@theSage21 could you please submit a pr for the web interface?
Thanks!

**Comment by jenniferzhu** [comment]
Thanks @minsangkim142 @theSage21 for opening a new issue on my question!
I think UI is a good idea to do the test. Without having an UI right now, how can I test it on the terminal?

**Comment by theSage21** [comment]
@jenniferzhu There's no live evaluation capability web/cli or otherwise AFAIK. We'll just have to wait for this feature to go in.

**Comment by jenniferzhu** [comment]
@theSage21 Thanks! I guess this will be an interesting feature to add!

**Comment by minsangkim142** [comment]
@theSage21 Yup I created a branch called "demo" where pushed a basic framework for R-net backend.
![image](https://user-images.githubusercontent.com/24954419/36578505-82236b5c-18c2-11e8-92ff-f59ff28147a2.png)
Could you have a look?

**Comment by minsangkim142** [comment]
Committed a working demo at "demo" branch.
![image](https://user-images.githubusercontent.com/24954419/36582134-2334f35a-18d5-11e8-9b94-1992545377cf.png)

**Comment by theSage21** [comment]
Bigger box :smile: as of https://github.com/theSage21/R-net/commit/1cb66e967d7ce3b2779ad625877fced02fe78c00

Does that work?

![image](https://user-images.githubusercontent.com/7693265/36633982-c516bb74-19c3-11e8-9cc8-6556ae8c8663.png)

**Comment by minsangkim142** [comment]
Merged to the master branch, thank you @theSage21
