### ISSUE TITLE
ValueError during embeddings reshaping

### ISSUE THREAD

**Issue by maciejbiesek** [minsangkim142/R-net#25]
Hi, I have a problem with training R-NET. After loading passage and question data I have the following error. 

`ValueError: cannot reshape array of size 27481500 into shape (91604,300)` 
in _model.py_ file in line:
`glove = np.reshape(glove,(Params.vocab_size,Params.emb_size))`

How to handle with that?

**Comment by theSage21** [comment]
You seem to have one more word in your glove file than what is expected. (91604 * 300) = 27481200 and your error has a difference of +300

Increasing `Params.vocab_size` by one show fix this error. I suspect that it's the  *space* word in glove files which is causing this.

**Comment by minsangkim142** [comment]
Hi @maciejbiesek, as @theSage21 said your glove probably has an additional word. The quick fix for now is just increasing Params.vocab_size by one. 
I will look into removing the dependency of vocab size as an additional information (delete Params.vocab_size) as it seems like people are getting different glove size depending on their spacy library version and so on.

**Comment by maciejbiesek** [comment]
Thank you very much, now it works! :)
