### ISSUE TITLE
Is their any saved model that can be used for demo?

### ISSUE THREAD

**Issue by sushgandhi** [minsangkim142/R-net#26]
if someone just wants to evaluate and see how the results are. it would be great if you could provide, your meta/data files for any model for download.

Thanks.!

**Comment by theSage21** [comment]
The project at [R-Net in tensorflow](https://github.com/unilight/R-NET-in-Tensorflow) has released weights. While weights are not released for this code you can try out that project's model. Performance is almost at par with this implementation.

**Comment by minsangkim142** [comment]
Hi @sushgandhi , while I don't have pretrained weights available for R-net demo, I have uploaded a pretrained weights for Google's [Fast Reading Comprehension](https://openreview.net/pdf?id=B14TlG-RW) implementation which achieves EM/F1 = 70.0/79.5. You can find it [here](https://github.com/minsangkim142/Fast-Reading-Comprehension).

**Comment by sushgandhi** [comment]
Thanks a lot @minsangkim142 and @theSage21
