### ISSUE TITLE
can't Preparing data.....

### ISSUE THREAD

**Issue by zhangxinars** [minsangkim142/R-net#32]
When I run "python model.py", In the Preparing data step, the process is always 0%,the output is:
Training...
Loading question data...
Loading passage data...
Preparing data...
Total number of trainable parameters: 1195735
Built model
Loading question data...
Loading passage data...
Preparing data...
  0%|                                         | 0/2064 [00:00<?, ?b/s]Killed
Thanks!

**Comment by minsangkim142** [comment]
Hi @zhangxinars It seems to me the model is running on cpu and killed due to an overtime. Make sure you're training on GPU otherwise this will take a long time.

**Comment by zhangxinars** [comment]
Thanks!
