### ISSUE TITLE
TypeError: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by monark12** [minsangkim142/R-net#4]
When I am running model.py I am getting this error in GRU.py file on line 46, in __init__

"super(gated_attention_GRUCell, self).__init__(_reuse=reuse) . TypeError: object.__init__() takes no parameters".
I am using python3.5. 
Please help me with this.

**Comment by minsangkim142** [comment]
Hey, please refer to issue #1 , the current version is not compatible with python3. You can run this code in python 2.7 using the following command.
```
python2 process.py --process True # for processing the data
python2 model.py  # for training/testing/debugging
```

**Comment by monark12** [comment]
I tried it with python2. Still getting the same error
